config:
    shim:
        'asap':
            exports: 'asap'
    paths:
        'asap': 'bundles/ororequirejs/lib/asap/asap.js'
        'requirejs-asap-init': 'bundles/ororequirejs/js/requirejs-asap-init.js'
